version: '3.8'

services:
    postgres:
        container_name: gerenciador_de_servico_postgres
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=2001
            - POSTGRES_DB=gerenciador_de_vagas
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: