spring.application.name=rodizioDeVagas
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_de_vagas
spring.datasource.username=postgres
spring.datasource.password=2001
spring.jpa.hibernate.ddl-auto=update

security.token.secret=GERENCIADOR_DE_VAGAS#

evolution.api.token=89effa3661fad9365b99e78f25b9df9f
evolution.api.url=https://chat.flowmasterhub.com/message/sendText/Breno

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===== CONFIGURAÇÕES REDIS =====
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=redis2001
spring.redis.timeout=5000
spring.redis.ssl.enabled=false

# Configurações dos eventos
app.redis.stream.fiscal-events=fiscal-events
app.redis.consumer.group=queue-service
app.redis.consumer.instance=instance-1

# Configurações de processamento
app.events.processing.batch-size=10
app.events.processing.timeout=3000




