spring.application.name=rodizioDeVagas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret=GERENCIADOR_DE_VAGAS#

evolution.api.token=89effa3661fad9365b99e78f25b9df9f
evolution.api.url=https://chat.flowmasterhub.com/message/sendText/Elaine

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.jackson.time-zone=America/Sao_Paulo
